export const uiVariables = {
  formMessage: document.querySelector('.form__message'),
  formEmail: document.querySelector('.form__email'),
  formCode: document.querySelector('.form__codeCheck'),
  formName: document.querySelector('.form__name'),
  entryMessage: document.querySelector('.entry__input'),
  entryEmail: document.querySelector('.input__email'),
  entryCode: document.querySelector('.input__code'),
  entryName: document.querySelector('#inputName'),
  dialogWindow: document.querySelector('.chat__dialogWindow'),
  messageUser: document.querySelector('#messageU'),
  btnExit: document.querySelector('.button__exit'),
  btnEnterCode: document.querySelector('.button__enterCode'),
  btnSettings: document.querySelector('.button__settings'),
  btnCrossSettings: document.querySelector('#crossSettings'),
  btnCrossCode: document.querySelector('#crossCode'),
  modAuthoriz: document.querySelector('#modalAuthorization'),
  modCode: document.querySelector('#modalCode'),
  modSettings: document.querySelector('#modalSettings'),
};
